### ISSUE TITLE
Generate all tables needed for OAuth 

### ISSUE THREAD

**Issue by maheshguruswamy** [strongloop/loopback-gateway#18]
I finally managed to get most of the OAuth piece wired up. I am trying to use the jwt flow to give another server access to my APIs. I get a correct 401 when the request is made without a token, but when I try to send it in with a token, I get this

{"error":"42P01","error_description":"relation \"public.oauthaccesstoken\" does not exist"}

I am guessing the tables to back the OAuth piece have not been created yet in my backend. I tried using the automigrate function like this

var loopback = require('loopback');
var loopbackoauth = require('loopback-component-oauth2');
var app = module.exports = loopback();
var ds = loopback.DataSource('loopback-connector-postgresql', { database: 'qeh' });
loopback.User.attachTo(ds);
loopback.Application.attachTo(ds);
loopback.RoleMapping.attachTo(ds);
loopback.AccessToken.attachTo(ds);
loopback.Role.attachTo(ds);
loopback.ACL.attachTo(ds);

loopbackoauth.OAuthAccessToken.attachTo(ds);
loopbackoauth.OAuthAuthorizationCode.attachTo(ds);
loopbackoauth.OAuthClientRegistration.attachTo(ds);
loopbackoauth.OAuthPermission.attachTo(ds);

ds.automigrate(['household','Application', 'User', 'ACL', 'AccessToken', 'Role', 'RoleMapping', 'OAuthAccessToken', 'OAuthAuthorizationCode','OAuthClientRegistration','OAuthPermission'], function(err) {
     console.log(err);
});

But I get an error saying 

loopbackoauth.OAuthAccessToken.attachTo(ds);
                               ^
TypeError: Cannot call method 'attachTo' of undefined
    at Object.<anonymous> (/Users/mahesh.guruswamy/Documents/qeh/qeh-api/server/bin/db-init.js:14:32)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

Any idea what is happening?

**Comment by zetflo** [comment]
It's not necessary ti attach Oauth Model with your Db.
This link is done by the init of component :

<pre>
var oauth2 = require('loopback-component-oauth2')(
    app, {
        dataSource: app.dataSources.yourDs
...
</pre>

My script to generate model : 

<pre>
var server = require('./server');
var dataSource = server.dataSources.myDS;
dataSource.automigrate(['OAuthAccessToken','OAuthAuthorizationCode','OAuthScope','OAuthScopeMapping','OAuthPermission','OAuthClientRegistration'], function(err){

    if (err) throw err;

    console.log('done');
});
</pre>

**Comment by maheshguruswamy** [comment]
Awesome. That worked. Now when I try to use node server/scripts/jwt-client-auth.js, I get this

eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiIxMjMiLCJzdWIiOiIxMjMiLCJhdWQiOiIvb2F1dGgvdG9rZW4iLCJleHAiOjE0MjUwNTMxOTM5NTMsIm
lhdCI6MTQyNTA1MzE4Mzk1Mywic2NvcGUiOlsiZGVtbyJdfQ.d6SdMdp_6jFqaVqXnULgVqHmZxhN1IGO7QWsgjFj_GvpoO-xz95-iGAzS-87NO
2_Yj7_c2TIYJfKRjrcdoJVHeLtYwm7L9ggL3hj7zfDRWI-idRSe32dQzEj63N_jK4JOq09LcZm8YCj9ooVqCNiyY31BcGooyyGqKNOmTWwySdzO
_tXNPDGmwmjnz9w4RL3x6uR68v_7-sZHLddg8CUzvtIDy7GHshUK_0zlHxyQ3YFM_bBADQJYyYmEAcH75BWVs4tAt8db8QqODtk_USXfgMbvFk5
bhIlmUxehxCT2DFdpSyOr035ADnYykb8UDrLcotCP_TU31vCTI_qBEM6dA
null 'Unauthorized'

So it generated something, but it never got persisted in the database. Any thoughts on what is causing the 'Unauthrozied' message?

**Comment by ltjin** [comment]
I have the same problem. 

My code like:
var oauth2 = require('loopback-component-oauth2')(
    app, {
        dataSource: app.dataSources.yourDs
...

when I try to use node server/scripts/rate-limiting-client.js, but i still get:
{"error":"ER_NO_SUCH_TABLE","error_description":"ER_NO_SUCH_TABLE: Table ....
the oauth models  don't created!

when I created the table,try again "node server/scripts/rate-limiting-client.js", i also get this:
Unauthorized
