### ISSUE TITLE
Cannot find module 'loopback'

### ISSUE THREAD

**Issue by sgentile** [strongloop/loopback-gateway#19]
I'm following along from the video: https://strongloop.com/strongblog/open-source-node-js-api-gateway/

When the video has the slc run .  I'm getting errors -

INFO strong-agent API key not found, StrongOps dashboard reporting disabled.
Generate configuration with:
    npm install -g strongloop
    slc strongops
See http://docs.strongloop.com/strong-agent for more information.
supervisor running without clustering (unsupervised)

module.js:340
    throw err;
          ^
Error: Cannot find module 'loopback'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/stevegentile/Documents/Workspace/Loopback/loopback-gateway/server/server.js:1:78)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/strongloop/node_modules/strong-supervisor/bin/sl-run.js:40:19)

**Comment by sgentile** [comment]
I sorted this out - was missing npm packages
